package eu.ecoepi.iris;

public enum CohortState {

    LARVAE_QUESTING, NYMPHS_QUESTING, ADULTS_QUESTING,
    LARVAE_QUESTING_INFECTED, NYMPHS_QUESTING_INFECTED,

    LARVAE_INACTIVE, NYMPHS_INACTIVE, ADULTS_INACTIVE,
    LARVAE_INACTIVE_INFECTED, NYMPHS_INACTIVE_INFECTED,

    LARVAE_ENGORGED, NYMPHS_ENGORGED, ADULTS_ENGORGED,
    LARVAE_ENGORGED_INFECTED, NYMPHS_ENGORGED_INFECTED,

    LARVAE_LATE_ENGORGED, NYMPHS_LATE_ENGORGED,
    LARVAE_LATE_ENGORGED_INFECTED, NYMPHS_LATE_ENGORGED_INFECTED,

    RODENTS, RODENTS_INFECTED

}