package eu.ecoepi.iris;

public enum LifeCycleStage {

    LARVAE_QUESTING, NYMPHS_QUESTING, ADULTS_QUESTING,
    LARVAE_INACTIVE, NYMPHS_INACTIVE, ADULTS_INACTIVE,
    LARVAE_ENGORGED, NYMPHS_ENGORGED, ADULTS_ENGORGED,
    LARVAE_LATE_ENGORGED, NYMPHS_LATE_ENGORGED,

}