package eu.ecoepi.iris;

public enum LifeCycleStage {

    LARVAE_QUESTING, NYMPH_QUESTING, ADULT_QUESTING,
    LARVAE_INACTIVE, NYMPH_INACTIVE, ADULT_INACTIVE,
    LARVAE_ENGORGED, NYMPH_ENGORGED, ADULT_ENGORGED,
    LARVAE_LATE_ENGORGED, NYMPHS_LATE_ENGORGED,

}